// flow-typed signature: 7986587ca804105e047fce2879c324b5
// flow-typed version: <<STUB>>/eslint-plugin-lodash_v^1.9.4/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-lodash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-lodash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-lodash/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/callback-binding' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/chain-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/collection-method-value' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/collection-return' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/consistent-compose' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/identity-shorthand' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/matches-prop-shorthand' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/matches-shorthand' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/no-commit' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/no-double-unwrap' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/no-extra-args' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/no-single-chain' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/path-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-chain' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-compact' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-constant' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-filter' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-flat-map' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-get' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-includes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-invoke-map' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-is-nil' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-lodash-chain' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-lodash-method' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-lodash-typecheck' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-map' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-matches' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-noop' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-over-quantifier' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-reject' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-startswith' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-thru' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-times' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prefer-wrapper-method' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/preferred-alias' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/prop-shorthand' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/rules/unwrap' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/util/astUtil' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/util/lodashUtil' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/util/methodDataByVersion' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/util/methodDataUtil' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash/lib/util/settingsUtil' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-lodash/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/index'>;
}
declare module 'eslint-plugin-lodash/lib/rules/callback-binding.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/callback-binding'>;
}
declare module 'eslint-plugin-lodash/lib/rules/chain-style.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/chain-style'>;
}
declare module 'eslint-plugin-lodash/lib/rules/collection-method-value.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/collection-method-value'>;
}
declare module 'eslint-plugin-lodash/lib/rules/collection-return.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/collection-return'>;
}
declare module 'eslint-plugin-lodash/lib/rules/consistent-compose.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/consistent-compose'>;
}
declare module 'eslint-plugin-lodash/lib/rules/identity-shorthand.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/identity-shorthand'>;
}
declare module 'eslint-plugin-lodash/lib/rules/matches-prop-shorthand.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/matches-prop-shorthand'>;
}
declare module 'eslint-plugin-lodash/lib/rules/matches-shorthand.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/matches-shorthand'>;
}
declare module 'eslint-plugin-lodash/lib/rules/no-commit.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/no-commit'>;
}
declare module 'eslint-plugin-lodash/lib/rules/no-double-unwrap.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/no-double-unwrap'>;
}
declare module 'eslint-plugin-lodash/lib/rules/no-extra-args.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/no-extra-args'>;
}
declare module 'eslint-plugin-lodash/lib/rules/no-single-chain.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/no-single-chain'>;
}
declare module 'eslint-plugin-lodash/lib/rules/path-style.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/path-style'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-chain.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-chain'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-compact.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-compact'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-constant.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-constant'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-filter.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-filter'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-flat-map.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-flat-map'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-get.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-get'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-includes.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-includes'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-invoke-map.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-invoke-map'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-is-nil.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-is-nil'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-lodash-chain.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-lodash-chain'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-lodash-method.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-lodash-method'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-lodash-typecheck.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-lodash-typecheck'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-map.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-map'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-matches.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-matches'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-noop.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-noop'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-over-quantifier.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-over-quantifier'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-reject.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-reject'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-startswith.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-startswith'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-thru.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-thru'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-times.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-times'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prefer-wrapper-method.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prefer-wrapper-method'>;
}
declare module 'eslint-plugin-lodash/lib/rules/preferred-alias.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/preferred-alias'>;
}
declare module 'eslint-plugin-lodash/lib/rules/prop-shorthand.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/prop-shorthand'>;
}
declare module 'eslint-plugin-lodash/lib/rules/unwrap.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/rules/unwrap'>;
}
declare module 'eslint-plugin-lodash/lib/util/astUtil.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/util/astUtil'>;
}
declare module 'eslint-plugin-lodash/lib/util/lodashUtil.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/util/lodashUtil'>;
}
declare module 'eslint-plugin-lodash/lib/util/methodDataByVersion.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/util/methodDataByVersion'>;
}
declare module 'eslint-plugin-lodash/lib/util/methodDataUtil.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/util/methodDataUtil'>;
}
declare module 'eslint-plugin-lodash/lib/util/settingsUtil.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash/lib/util/settingsUtil'>;
}
