// flow-typed signature: 45920d2cbbf2d453e33984ee5f8d7a63
// flow-typed version: <<STUB>>/eslint-plugin-goodeggs_v^3.3.2/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-goodeggs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-goodeggs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-goodeggs/build/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-goodeggs/build/rules/group_imports/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-goodeggs/src/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-goodeggs/src/rules/group_imports/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-goodeggs/build/index.js' {
  declare module.exports: $Exports<'eslint-plugin-goodeggs/build/index'>;
}
declare module 'eslint-plugin-goodeggs/build/rules/group_imports/index.js' {
  declare module.exports: $Exports<'eslint-plugin-goodeggs/build/rules/group_imports/index'>;
}
declare module 'eslint-plugin-goodeggs/src/index.js' {
  declare module.exports: $Exports<'eslint-plugin-goodeggs/src/index'>;
}
declare module 'eslint-plugin-goodeggs/src/rules/group_imports/index.js' {
  declare module.exports: $Exports<'eslint-plugin-goodeggs/src/rules/group_imports/index'>;
}
