// flow-typed signature: 4a3ff353a49afdda5f3a52640ad613d5
// flow-typed version: <<STUB>>/goodeggs-test-helpers_v^1.4.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'goodeggs-test-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'goodeggs-test-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'goodeggs-test-helpers/browser' {
  declare module.exports: any;
}

declare module 'goodeggs-test-helpers/chai' {
  declare module.exports: any;
}

declare module 'goodeggs-test-helpers/exec_file_as_test' {
  declare module.exports: any;
}

declare module 'goodeggs-test-helpers/flow' {
  declare module.exports: any;
}

declare module 'goodeggs-test-helpers/global_browser_shim' {
  declare module.exports: any;
}

declare module 'goodeggs-test-helpers/global' {
  declare module.exports: any;
}

declare module 'goodeggs-test-helpers/globals' {
  declare module.exports: any;
}

declare module 'goodeggs-test-helpers/mocha_context' {
  declare module.exports: any;
}

declare module 'goodeggs-test-helpers/server' {
  declare module.exports: any;
}

declare module 'goodeggs-test-helpers/sinon_webpack_shim' {
  declare module.exports: any;
}

// Filename aliases
declare module 'goodeggs-test-helpers/browser.js' {
  declare module.exports: $Exports<'goodeggs-test-helpers/browser'>;
}
declare module 'goodeggs-test-helpers/chai.js' {
  declare module.exports: $Exports<'goodeggs-test-helpers/chai'>;
}
declare module 'goodeggs-test-helpers/exec_file_as_test.js' {
  declare module.exports: $Exports<'goodeggs-test-helpers/exec_file_as_test'>;
}
declare module 'goodeggs-test-helpers/flow.js' {
  declare module.exports: $Exports<'goodeggs-test-helpers/flow'>;
}
declare module 'goodeggs-test-helpers/global_browser_shim.js' {
  declare module.exports: $Exports<'goodeggs-test-helpers/global_browser_shim'>;
}
declare module 'goodeggs-test-helpers/global.js' {
  declare module.exports: $Exports<'goodeggs-test-helpers/global'>;
}
declare module 'goodeggs-test-helpers/globals.js' {
  declare module.exports: $Exports<'goodeggs-test-helpers/globals'>;
}
declare module 'goodeggs-test-helpers/index' {
  declare module.exports: $Exports<'goodeggs-test-helpers'>;
}
declare module 'goodeggs-test-helpers/index.js' {
  declare module.exports: $Exports<'goodeggs-test-helpers'>;
}
declare module 'goodeggs-test-helpers/mocha_context.js' {
  declare module.exports: $Exports<'goodeggs-test-helpers/mocha_context'>;
}
declare module 'goodeggs-test-helpers/server.js' {
  declare module.exports: $Exports<'goodeggs-test-helpers/server'>;
}
declare module 'goodeggs-test-helpers/sinon_webpack_shim.js' {
  declare module.exports: $Exports<'goodeggs-test-helpers/sinon_webpack_shim'>;
}
